apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: salat-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: "salatbar.secova.net" # Change this to your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: salat
                port:
                  name: salatbar
